# Generated by Django 6.1.1 on 2026-09-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FazUno', '0003_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='prestadores',
            field=models.ManyToManyField(related_name='servicos', to='FazUno.perfil'),
        ),
    ]
