"""
Django settings for FazUno project.

Generated by 'django-admin startproject' using Django 6.1.1.
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-kjdt@o+i)9s@_#x&#$0(0yi1uo)v)*0-(y7z*te77w#@)1@f2a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'rest_framework', 
    'django.contrib.admin',# Permite que o Next.js comunique com o Django
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'FazUno',  # ← SUBISTITUA PELO NOME DO SEU APP (ex: 'autenticacao', 'usuarios', etc.)
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Deve ficar no topo para interceptar as requisições do Next.js
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'FazUno.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'FazUno.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# ==============================================================================
# CONFIGURAÇÃO DE E-MAIL
# ==============================================================================

# OPÇÃO A: Modo de Desenvolvimento (Imprime o e-mail no Terminal do Django)
# Ideal para testar sem precisar configurar SMTP de verdade agora
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'FazUno <suporte@fazuno.com.br>'

# OPÇÃO B: Para enviar e-mails reais (Exemplo SMTP Gmail / SendGrid / etc)
# Quando for para produção, comente a OPÇÃO A e descomente este bloco:
"""
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'seu-email@gmail.com'
EMAIL_HOST_PASSWORD = 'sua-senha-de-aplicativo'
DEFAULT_FROM_EMAIL = 'FazUno <seu-email@gmail.com>'
"""


# ==============================================================================
# CONFIGURAÇÃO DE INTEGRAÇÃO COM NEXT.JS (CORS)
# ==============================================================================

# Autoriza o Next.js (a correr na porta 3000) a fazer pedidos ao Django
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

# Permite que o navegador envie cookies e credenciais de sessão entre as duas aplicações
CORS_ALLOW_CREDENTIALS = True


# ==============================================================================
# CONFIGURAÇÃO DO DJANGO REST FRAMEWORK
# ==============================================================================

# Com SessionAuthentication ativa, as views com @api_view retornam 403 por
# CSRF após o login. Desativamos a autenticação de sessão do DRF e liberamos
# o acesso, já que a autenticação da aplicação é feita nas próprias views.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
}